export const MUSIC_BOARD_ABI = [
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "id", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "author", "type": "address" }, { "indexed": false, "internalType": "string", "name": "track", "type": "string" }, { "indexed": false, "internalType": "string", "name": "aliasName", "type": "string" }, { "indexed": false, "internalType": "uint64", "name": "timestamp", "type": "uint64" } ], "name": "NoteAdded", "type": "event" },
  { "anonymous": false, "inputs": [ { "indexed": true, "internalType": "uint256", "name": "id", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "sender", "type": "address" } ], "name": "NoteApplauded", "type": "event" },
  { "inputs": [ { "internalType": "string", "name": "track", "type": "string" }, { "internalType": "string", "name": "message", "type": "string" }, { "internalType": "string", "name": "aliasName", "type": "string" } ], "name": "addNote", "outputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" } ], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "externalEuint32", "name": "plusOneExt", "type": "bytes32" }, { "internalType": "bytes", "name": "inputProof", "type": "bytes" } ], "name": "applaudNote", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" } ], "name": "getApplauseHandle", "outputs": [ { "internalType": "euint32", "name": "", "type": "bytes32" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" } ], "name": "getApplausePlain", "outputs": [ { "internalType": "uint32", "name": "", "type": "uint32" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [ { "internalType": "uint256", "name": "id", "type": "uint256" } ], "name": "getNote", "outputs": [ { "internalType": "uint256", "name": "noteId", "type": "uint256" }, { "internalType": "address", "name": "author", "type": "address" }, { "internalType": "string", "name": "track", "type": "string" }, { "internalType": "string", "name": "message", "type": "string" }, { "internalType": "string", "name": "aliasName", "type": "string" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "getNotes", "outputs": [ { "components": [ { "internalType": "uint256", "name": "id", "type": "uint256" }, { "internalType": "address", "name": "author", "type": "address" }, { "internalType": "string", "name": "track", "type": "string" }, { "internalType": "string", "name": "message", "type": "string" }, { "internalType": "string", "name": "aliasName", "type": "string" }, { "internalType": "uint64", "name": "timestamp", "type": "uint64" }, { "internalType": "euint32", "name": "applause", "type": "bytes32" }, { "internalType": "uint32", "name": "applausePlain", "type": "uint32" } ], "internalType": "struct MusicBoard.NoteItem[]", "name": "items", "type": "tuple[]" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "nextId", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "protocolId", "outputs": [ { "internalType": "uint256", "name": "", "type": "uint256" } ], "stateMutability": "pure", "type": "function" }
];


